// Generated by:
//   supabase gen types typescript --local --schema app > src/lib/database.types.ts
// Do not hand-edit. Regenerate after any migration change (see
// supabase/tests/run.ts / pnpm db:reset to apply migrations locally first).

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  app: {
    Tables: {
      ai_model_prices: {
        Row: {
          cache_read_usd_per_mtok: number
          cache_write_usd_per_mtok: number
          effective_from: string
          input_usd_per_mtok: number
          model: string
          output_usd_per_mtok: number
        }
        Insert: {
          cache_read_usd_per_mtok: number
          cache_write_usd_per_mtok: number
          effective_from?: string
          input_usd_per_mtok: number
          model: string
          output_usd_per_mtok: number
        }
        Update: {
          cache_read_usd_per_mtok?: number
          cache_write_usd_per_mtok?: number
          effective_from?: string
          input_usd_per_mtok?: number
          model?: string
          output_usd_per_mtok?: number
        }
        Relationships: []
      }
      ai_profile_budget: {
        Row: {
          budget_per_minute: number
          profile_id: string
          tokens_used: number
          window_started_at: string
        }
        Insert: {
          budget_per_minute?: number
          profile_id: string
          tokens_used?: number
          window_started_at?: string
        }
        Update: {
          budget_per_minute?: number
          profile_id?: string
          tokens_used?: number
          window_started_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "ai_profile_budget_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      ai_rate_budget: {
        Row: {
          budget_per_minute: number
          id: boolean
          tokens_used: number
          window_started_at: string
        }
        Insert: {
          budget_per_minute?: number
          id?: boolean
          tokens_used?: number
          window_started_at?: string
        }
        Update: {
          budget_per_minute?: number
          id?: boolean
          tokens_used?: number
          window_started_at?: string
        }
        Relationships: []
      }
      ai_usage: {
        Row: {
          cache_read: number
          cache_write: number
          function: string
          household_id: string | null
          id: number
          import_job_id: string | null
          lane: string
          latency_ms: number | null
          model: string
          occurred_at: string
          ok: boolean
          profile_id: string | null
          reason: string | null
          request_id: string | null
          tokens_in: number
          tokens_out: number
        }
        Insert: {
          cache_read?: number
          cache_write?: number
          function: string
          household_id?: string | null
          id?: never
          import_job_id?: string | null
          lane: string
          latency_ms?: number | null
          model: string
          occurred_at?: string
          ok?: boolean
          profile_id?: string | null
          reason?: string | null
          request_id?: string | null
          tokens_in?: number
          tokens_out?: number
        }
        Update: {
          cache_read?: number
          cache_write?: number
          function?: string
          household_id?: string | null
          id?: never
          import_job_id?: string | null
          lane?: string
          latency_ms?: number | null
          model?: string
          occurred_at?: string
          ok?: boolean
          profile_id?: string | null
          reason?: string | null
          request_id?: string | null
          tokens_in?: number
          tokens_out?: number
        }
        Relationships: [
          {
            foreignKeyName: "ai_usage_household_id_fkey"
            columns: ["household_id"]
            isOneToOne: false
            referencedRelation: "households"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ai_usage_import_job_id_fkey"
            columns: ["import_job_id"]
            isOneToOne: false
            referencedRelation: "import_jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ai_usage_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      analytics_events: {
        Row: {
          created_at: string
          display_mode: string | null
          event: string
          household_id: string | null
          id: number
          occurred_at: string
          profile_id: string | null
          props: Json
          release_sha: string | null
          session_id: string
        }
        Insert: {
          created_at?: string
          display_mode?: string | null
          event: string
          household_id?: string | null
          id?: never
          occurred_at?: string
          profile_id?: string | null
          props?: Json
          release_sha?: string | null
          session_id: string
        }
        Update: {
          created_at?: string
          display_mode?: string | null
          event?: string
          household_id?: string | null
          id?: never
          occurred_at?: string
          profile_id?: string | null
          props?: Json
          release_sha?: string | null
          session_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "analytics_events_household_id_fkey"
            columns: ["household_id"]
            isOneToOne: false
            referencedRelation: "households"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "analytics_events_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      app_admins: {
        Row: {
          created_at: string
          profile_id: string
        }
        Insert: {
          created_at?: string
          profile_id: string
        }
        Update: {
          created_at?: string
          profile_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "app_admins_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      feature_flags: {
        Row: {
          enabled: boolean
          key: string
          rollout_percent: number
          updated_at: string
        }
        Insert: {
          enabled?: boolean
          key: string
          rollout_percent?: number
          updated_at?: string
        }
        Update: {
          enabled?: boolean
          key?: string
          rollout_percent?: number
          updated_at?: string
        }
        Relationships: []
      }
      follows: {
        Row: {
          created_at: string
          followed_household_id: string
          follower_household_id: string
        }
        Insert: {
          created_at?: string
          followed_household_id: string
          follower_household_id: string
        }
        Update: {
          created_at?: string
          followed_household_id?: string
          follower_household_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "follows_followed_household_id_fkey"
            columns: ["followed_household_id"]
            isOneToOne: false
            referencedRelation: "households"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "follows_follower_household_id_fkey"
            columns: ["follower_household_id"]
            isOneToOne: false
            referencedRelation: "households"
            referencedColumns: ["id"]
          },
        ]
      }
      household_follow_codes: {
        Row: {
          code: string
          created_at: string
          created_by: string
          expires_at: string
          household_id: string
        }
        Insert: {
          code: string
          created_at?: string
          created_by: string
          expires_at?: string
          household_id: string
        }
        Update: {
          code?: string
          created_at?: string
          created_by?: string
          expires_at?: string
          household_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "household_follow_codes_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "household_follow_codes_household_id_fkey"
            columns: ["household_id"]
            isOneToOne: false
            referencedRelation: "households"
            referencedColumns: ["id"]
          },
        ]
      }
      household_invites: {
        Row: {
          code: string
          created_at: string
          created_by: string
          expires_at: string
          household_id: string
          redeemed_at: string | null
          redeemed_by: string | null
        }
        Insert: {
          code: string
          created_at?: string
          created_by: string
          expires_at?: string
          household_id: string
          redeemed_at?: string | null
          redeemed_by?: string | null
        }
        Update: {
          code?: string
          created_at?: string
          created_by?: string
          expires_at?: string
          household_id?: string
          redeemed_at?: string | null
          redeemed_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "household_invites_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "household_invites_household_id_fkey"
            columns: ["household_id"]
            isOneToOne: false
            referencedRelation: "households"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "household_invites_redeemed_by_fkey"
            columns: ["redeemed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      household_members: {
        Row: {
          household_id: string
          joined_at: string
          profile_id: string
          role: string
        }
        Insert: {
          household_id: string
          joined_at?: string
          profile_id: string
          role: string
        }
        Update: {
          household_id?: string
          joined_at?: string
          profile_id?: string
          role?: string
        }
        Relationships: [
          {
            foreignKeyName: "household_members_household_id_fkey"
            columns: ["household_id"]
            isOneToOne: false
            referencedRelation: "households"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "household_members_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      households: {
        Row: {
          allowed_tags: string[]
          created_at: string
          id: string
          is_personal: boolean
          name: string
          owner_profile_id: string
          primary_tags: string[]
          updated_at: string
        }
        Insert: {
          allowed_tags?: string[]
          created_at?: string
          id?: string
          is_personal?: boolean
          name: string
          owner_profile_id: string
          primary_tags?: string[]
          updated_at?: string
        }
        Update: {
          allowed_tags?: string[]
          created_at?: string
          id?: string
          is_personal?: boolean
          name?: string
          owner_profile_id?: string
          primary_tags?: string[]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "households_owner_profile_id_fkey"
            columns: ["owner_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      import_jobs: {
        Row: {
          completed_at: string | null
          created_at: string
          error: string | null
          household_id: string
          id: string
          kind: string
          payload: Json
          phase: string | null
          profile_id: string
          progress_text: string | null
          recipe_id: string | null
          status: string
        }
        Insert: {
          completed_at?: string | null
          created_at?: string
          error?: string | null
          household_id: string
          id?: string
          kind: string
          payload?: Json
          phase?: string | null
          profile_id: string
          progress_text?: string | null
          recipe_id?: string | null
          status: string
        }
        Update: {
          completed_at?: string | null
          created_at?: string
          error?: string | null
          household_id?: string
          id?: string
          kind?: string
          payload?: Json
          phase?: string | null
          profile_id?: string
          progress_text?: string | null
          recipe_id?: string | null
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "import_jobs_household_id_fkey"
            columns: ["household_id"]
            isOneToOne: false
            referencedRelation: "households"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "import_jobs_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "import_jobs_recipe_id_fkey"
            columns: ["recipe_id"]
            isOneToOne: false
            referencedRelation: "recipes"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string
          display_name: string
          id: string
          locale: string
          preferred_language: string
          preferred_unit_system: string
          updated_at: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          display_name: string
          id: string
          locale?: string
          preferred_language?: string
          preferred_unit_system?: string
          updated_at?: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          display_name?: string
          id?: string
          locale?: string
          preferred_language?: string
          preferred_unit_system?: string
          updated_at?: string
        }
        Relationships: []
      }
      recipe_chat_messages: {
        Row: {
          chat_session_id: string
          content: string
          created_at: string
          id: string
          role: string
        }
        Insert: {
          chat_session_id: string
          content: string
          created_at?: string
          id?: string
          role: string
        }
        Update: {
          chat_session_id?: string
          content?: string
          created_at?: string
          id?: string
          role?: string
        }
        Relationships: [
          {
            foreignKeyName: "recipe_chat_messages_chat_session_id_fkey"
            columns: ["chat_session_id"]
            isOneToOne: false
            referencedRelation: "recipe_chat_sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      recipe_chat_sessions: {
        Row: {
          agent_cycles: number
          anthropic_session_id: string
          created_at: string
          created_by: string
          current_draft: Json | null
          draft_repair_attempts: number
          events_cursor: string | null
          household_id: string
          id: string
          recipe_id: string | null
          status: string
          title: string | null
          updated_at: string
        }
        Insert: {
          agent_cycles?: number
          anthropic_session_id: string
          created_at?: string
          created_by: string
          current_draft?: Json | null
          draft_repair_attempts?: number
          events_cursor?: string | null
          household_id: string
          id?: string
          recipe_id?: string | null
          status?: string
          title?: string | null
          updated_at?: string
        }
        Update: {
          agent_cycles?: number
          anthropic_session_id?: string
          created_at?: string
          created_by?: string
          current_draft?: Json | null
          draft_repair_attempts?: number
          events_cursor?: string | null
          household_id?: string
          id?: string
          recipe_id?: string | null
          status?: string
          title?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "recipe_chat_sessions_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "recipe_chat_sessions_household_id_fkey"
            columns: ["household_id"]
            isOneToOne: false
            referencedRelation: "households"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "recipe_chat_sessions_recipe_id_fkey"
            columns: ["recipe_id"]
            isOneToOne: false
            referencedRelation: "recipes"
            referencedColumns: ["id"]
          },
        ]
      }
      recipe_ingredients: {
        Row: {
          id: string
          ingredient_name: string | null
          notes: string | null
          position: number
          quantity: Json | null
          raw_text: string
          recipe_id: string
          section: string | null
          unit: string | null
        }
        Insert: {
          id?: string
          ingredient_name?: string | null
          notes?: string | null
          position: number
          quantity?: Json | null
          raw_text: string
          recipe_id: string
          section?: string | null
          unit?: string | null
        }
        Update: {
          id?: string
          ingredient_name?: string | null
          notes?: string | null
          position?: number
          quantity?: Json | null
          raw_text?: string
          recipe_id?: string
          section?: string | null
          unit?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "recipe_ingredients_recipe_id_fkey"
            columns: ["recipe_id"]
            isOneToOne: false
            referencedRelation: "recipes"
            referencedColumns: ["id"]
          },
        ]
      }
      recipe_links: {
        Row: {
          created_at: string
          created_by: string
          household_id: string
          recipe_id: string
        }
        Insert: {
          created_at?: string
          created_by: string
          household_id: string
          recipe_id: string
        }
        Update: {
          created_at?: string
          created_by?: string
          household_id?: string
          recipe_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "recipe_links_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "recipe_links_household_id_fkey"
            columns: ["household_id"]
            isOneToOne: false
            referencedRelation: "households"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "recipe_links_recipe_id_fkey"
            columns: ["recipe_id"]
            isOneToOne: false
            referencedRelation: "recipes"
            referencedColumns: ["id"]
          },
        ]
      }
      recipe_shares: {
        Row: {
          created_at: string
          created_by: string | null
          recipe_id: string
          token: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          recipe_id: string
          token?: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          recipe_id?: string
          token?: string
        }
        Relationships: [
          {
            foreignKeyName: "recipe_shares_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "recipe_shares_recipe_id_fkey"
            columns: ["recipe_id"]
            isOneToOne: true
            referencedRelation: "recipes"
            referencedColumns: ["id"]
          },
        ]
      }
      recipe_steps: {
        Row: {
          body: string
          duration_min: number | null
          id: string
          position: number
          recipe_id: string
        }
        Insert: {
          body: string
          duration_min?: number | null
          id?: string
          position: number
          recipe_id: string
        }
        Update: {
          body?: string
          duration_min?: number | null
          id?: string
          position?: number
          recipe_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "recipe_steps_recipe_id_fkey"
            columns: ["recipe_id"]
            isOneToOne: false
            referencedRelation: "recipes"
            referencedColumns: ["id"]
          },
        ]
      }
      recipe_tags: {
        Row: {
          recipe_id: string
          tag: string
        }
        Insert: {
          recipe_id: string
          tag: string
        }
        Update: {
          recipe_id?: string
          tag?: string
        }
        Relationships: [
          {
            foreignKeyName: "recipe_tags_recipe_id_fkey"
            columns: ["recipe_id"]
            isOneToOne: false
            referencedRelation: "recipes"
            referencedColumns: ["id"]
          },
        ]
      }
      recipe_translations: {
        Row: {
          created_at: string
          language: string
          payload: Json
          recipe_id: string
          source_hash: string
        }
        Insert: {
          created_at?: string
          language: string
          payload: Json
          recipe_id: string
          source_hash: string
        }
        Update: {
          created_at?: string
          language?: string
          payload?: Json
          recipe_id?: string
          source_hash?: string
        }
        Relationships: [
          {
            foreignKeyName: "recipe_translations_recipe_id_fkey"
            columns: ["recipe_id"]
            isOneToOne: false
            referencedRelation: "recipes"
            referencedColumns: ["id"]
          },
        ]
      }
      recipes: {
        Row: {
          canonical_unit_system: string
          created_at: string
          created_by: string
          description: string | null
          hero_image_path: string | null
          household_id: string
          id: string
          search: unknown
          servings: number
          source_language: string
          source_type: string
          source_url: string | null
          title: string
          total_time_min: number | null
          updated_at: string
        }
        Insert: {
          canonical_unit_system: string
          created_at?: string
          created_by: string
          description?: string | null
          hero_image_path?: string | null
          household_id: string
          id?: string
          search?: unknown
          servings: number
          source_language?: string
          source_type: string
          source_url?: string | null
          title: string
          total_time_min?: number | null
          updated_at?: string
        }
        Update: {
          canonical_unit_system?: string
          created_at?: string
          created_by?: string
          description?: string | null
          hero_image_path?: string | null
          household_id?: string
          id?: string
          search?: unknown
          servings?: number
          source_language?: string
          source_type?: string
          source_url?: string | null
          title?: string
          total_time_min?: number | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "recipes_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "recipes_household_id_fkey"
            columns: ["household_id"]
            isOneToOne: false
            referencedRelation: "households"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      v_ai_daily_cost: {
        Row: {
          day: string | null
          household_id: string | null
          jobs: number | null
          tokens_in: number | null
          tokens_out: number | null
          tokens_total: number | null
        }
        Relationships: [
          {
            foreignKeyName: "import_jobs_household_id_fkey"
            columns: ["household_id"]
            isOneToOne: false
            referencedRelation: "households"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      add_follow: {
        Args: { p_code: string; p_follower_household: string }
        Returns: string
      }
      can_read_recipe_image: { Args: { p_name: string }; Returns: boolean }
      create_follow_code: { Args: { p_household: string }; Returns: string }
      create_invite: { Args: { p_household: string }; Returns: string }
      delete_household: { Args: { p_household: string }; Returns: undefined }
      filter_household_tags: {
        Args: { p_household: string; p_tags: Json }
        Returns: string[]
      }
      gen_base32: { Args: { p_len: number }; Returns: string }
      gen_share_token: { Args: never; Returns: string }
      get_public_recipe: { Args: { share_token: string }; Returns: Json }
      is_app_admin: { Args: never; Returns: boolean }
      is_chat_session_editor: { Args: { s: string }; Returns: boolean }
      is_chat_session_visible: { Args: { s: string }; Returns: boolean }
      is_household_creator: { Args: { h: string }; Returns: boolean }
      is_household_editor: { Args: { h: string }; Returns: boolean }
      is_household_follower: { Args: { h: string }; Returns: boolean }
      is_household_member: { Args: { h: string }; Returns: boolean }
      is_household_owner: { Args: { h: string }; Returns: boolean }
      is_recipe_editor: { Args: { p_recipe: string }; Returns: boolean }
      is_recipe_in_household: {
        Args: { h: string; p_recipe: string }
        Returns: boolean
      }
      is_recipe_visible: { Args: { p_recipe: string }; Returns: boolean }
      is_safe_hero_image_path: {
        Args: { p_current?: string; p_path: string }
        Returns: boolean
      }
      is_valid_household_tags: { Args: { tags: string[] }; Returns: boolean }
      leave_household: { Args: { p_household: string }; Returns: undefined }
      leave_household_with_recipes: {
        Args: { p_household: string }
        Returns: string
      }
      list_household_followers: {
        Args: { p_household: string }
        Returns: {
          created_at: string
          follower_household_id: string
          name: string
        }[]
      }
      metrics_active_users: {
        Args: { p_from: string; p_to: string }
        Returns: {
          dau: number
          day: string
          mau_rolling: number
          wau_rolling: number
        }[]
      }
      metrics_ai_cost: {
        Args: { p_from: string; p_to: string }
        Returns: {
          cache_read: number
          cache_write: number
          calls: number
          day: string
          function: string
          model: string
          tokens_in: number
          tokens_out: number
          unpriced_calls: number
          usd: number
        }[]
      }
      metrics_app_opens: {
        Args: { p_from: string; p_to: string }
        Returns: {
          day: string
          opens: number
          resumes: number
          standalone_opens: number
          unique_sessions: number
        }[]
      }
      metrics_edge_failures: {
        Args: { p_from: string; p_to: string }
        Returns: {
          calls: number
          day: string
          fn: string
          outcome: string
          p95_ms: number
        }[]
      }
      metrics_imports: {
        Args: { p_from: string; p_to: string }
        Returns: {
          day: string
          failed: number
          kind: string
          p50_ms: number
          p95_ms: number
          started: number
          succeeded: number
        }[]
      }
      metrics_stuck_imports: {
        Args: never
        Returns: {
          age_minutes: number
          created_at: string
          household_id: string
          id: string
          kind: string
          profile_id: string
          status: string
        }[]
      }
      normalize_quantity: { Args: { q: Json }; Returns: Json }
      peek_follow_code: { Args: { p_code: string }; Returns: Json }
      popular_tags: {
        Args: { p_household_ids: string[]; p_limit?: number }
        Returns: {
          n: number
          tag: string
        }[]
      }
      promote_hero_image: {
        Args: { p_import_path: string; p_recipe: string }
        Returns: undefined
      }
      quantity_jsonb_to_numeric: { Args: { q: Json }; Returns: number }
      reap_analytics_events: { Args: never; Returns: number }
      reap_stuck_imports: { Args: never; Returns: number }
      redeem_invite: { Args: { p_code: string }; Returns: string }
      save_recipe: {
        Args: { p_draft: Json; p_household: string }
        Returns: string
      }
      search_recipes: {
        Args: { household_ids: string[]; q: string }
        Returns: {
          canonical_unit_system: string
          created_at: string
          created_by: string
          description: string | null
          hero_image_path: string | null
          household_id: string
          id: string
          search: unknown
          servings: number
          source_language: string
          source_type: string
          source_url: string | null
          title: string
          total_time_min: number | null
          updated_at: string
        }[]
        SetofOptions: {
          from: "*"
          to: "recipes"
          isOneToOne: false
          isSetofReturn: true
        }
      }
      transfer_ownership: {
        Args: { p_household: string; p_new_owner: string }
        Returns: undefined
      }
      update_recipe: {
        Args: { p_draft: Json; p_expected_updated_at?: string; p_id: string }
        Returns: undefined
      }
      v_ai_daily_cost_for_household: {
        Args: { p_household: string }
        Returns: {
          day: string
          household_id: string
          jobs: number
          tokens_in: number
          tokens_out: number
          tokens_total: number
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  app: {
    Enums: {},
  },
} as const

