import { refreshAuthDerivedState, useAuth } from '@/lib/auth';
import { type RedeemInviteInput, RedeemInviteSchema } from '@/lib/forms/household';
import { supabase } from '@/lib/supabase';
import { translateHouseholdError } from '@/ui/household/translateError';
import { Button } from '@/ui/primitives/Button';
import { Card } from '@/ui/primitives/Card';
import { Input } from '@/ui/primitives/Input';
import { zodResolver } from '@hookform/resolvers/zod';
import { createFileRoute, useNavigate } from '@tanstack/react-router';
import { useEffect, useState } from 'react';
import { useForm } from 'react-hook-form';
import { useTranslation } from 'react-i18next';
import { requireAuth } from '../_guards';

// New users get a personal household at signup, so this page is no longer
// an onboarding gate. It survives as a thin invite-redeem landing for the
// share links generated by InviteCodeDialog (origin/onboarding?code=…).
// If there's no code in the URL we bounce to the home redirect.
export const Route = createFileRoute('/onboarding/')({
  beforeLoad: requireAuth,
  validateSearch: (search: Record<string, unknown>): { code?: string } => {
    const raw = typeof search.code === 'string' ? search.code : undefined;
    if (!raw) return {};
    // Accept lowercase/mixed-case codes from pasted links and normalize to the
    // canonical uppercase form the redeem RPC and schema expect.
    const normalized = raw.trim().toUpperCase();
    return /^[A-Z2-7]{8}$/.test(normalized) ? { code: normalized } : {};
  },
  component: OnboardingPage,
});

function OnboardingPage() {
  const { t } = useTranslation();
  const { code: prefilledCode } = Route.useSearch();
  const nav = useNavigate();
  const auth = useAuth();
  const [serverError, setServerError] = useState<string | null>(null);

  const redeem = useForm<RedeemInviteInput>({
    resolver: zodResolver(RedeemInviteSchema),
    defaultValues: prefilledCode ? { code: prefilledCode } : undefined,
  });

  useEffect(() => {
    if (prefilledCode) {
      redeem.setValue('code', prefilledCode, { shouldValidate: true });
    }
  }, [prefilledCode, redeem]);

  // No code in the URL? There's no longer any "create a household" step
  // here, so just send the user to the home redirect — it'll resolve to
  // their personal household.
  useEffect(() => {
    if (!prefilledCode) {
      void nav({ to: '/' });
    }
  }, [prefilledCode, nav]);

  // When the caller is solo (only in their personal household) the RPC
  // will merge their recipes into the target. Surface a heads-up so the
  // user understands the move before they confirm.
  const solo = auth.memberships.length === 1 && auth.memberships[0]?.is_personal;

  return (
    <main className="min-h-dvh px-4 py-12 grid grid-cols-1 gap-6 max-w-lg mx-auto">
      <Card className="p-6">
        <h2 className="font-display text-2xl mb-4">{t('household.redeem_title')}</h2>
        {prefilledCode && (
          <p className="text-sage-ink bg-sage/30 rounded-[var(--radius-md)] px-3 py-2 text-sm mb-3">
            {t('household.invite_prefilled')}
          </p>
        )}
        {solo && (
          <div className="rounded-[var(--radius-md)] border border-saffron/40 bg-saffron/10 px-3 py-3 mb-3">
            <p className="font-display text-base text-aubergine mb-1">
              {t('household.merge_notice_title')}
            </p>
            <p className="text-ink-soft text-sm leading-relaxed">{t('household.merge_notice')}</p>
          </div>
        )}
        <form
          className="space-y-3"
          onSubmit={redeem.handleSubmit(async (values) => {
            if (!auth.user) return;
            setServerError(null);
            const { data, error } = await supabase.rpc('redeem_invite', { p_code: values.code });
            if (error) {
              setServerError(translateHouseholdError(t, error));
              return;
            }
            const householdId = data as unknown as string;
            // Memberships and household membership counts both changed.
            await refreshAuthDerivedState(auth.user.id);
            await nav({ to: '/h/$householdId', params: { householdId } });
          })}
        >
          <Input
            placeholder={t('household.invite_placeholder')}
            autoFocus={!!prefilledCode}
            aria-invalid={redeem.formState.errors.code ? true : undefined}
            aria-describedby={redeem.formState.errors.code ? 'redeem-code-error' : undefined}
            {...redeem.register('code')}
          />
          {redeem.formState.errors.code && (
            <p id="redeem-code-error" role="alert" className="text-pomegranate text-sm">
              {redeem.formState.errors.code.message}
            </p>
          )}
          <Button type="submit" className="w-full">
            {t('household.redeem')}
          </Button>
        </form>
        {serverError && (
          <p role="alert" aria-live="assertive" className="text-pomegranate text-sm mt-3">
            {serverError}
          </p>
        )}
      </Card>
    </main>
  );
}
