/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as FollowingIndexRouteImport } from './routes/following/index'
import { Route as AuthUpdatePasswordRouteImport } from './routes/auth/update-password'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthResetRouteImport } from './routes/auth/reset'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as HHouseholdIdIndexRouteImport } from './routes/h/$householdId/index'
import { Route as HHouseholdIdSettingsRouteImport } from './routes/h/$householdId/settings'
import { Route as HHouseholdIdImportRouteImport } from './routes/h/$householdId/import'
import { Route as HHouseholdIdRRecipeIdIndexRouteImport } from './routes/h/$householdId/r/$recipeId/index'
import { Route as HHouseholdIdRRecipeIdEditRouteImport } from './routes/h/$householdId/r/$recipeId/edit'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowingIndexRoute = FollowingIndexRouteImport.update({
  id: '/following/',
  path: '/following/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUpdatePasswordRoute = AuthUpdatePasswordRouteImport.update({
  id: '/auth/update-password',
  path: '/auth/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/auth/reset',
  path: '/auth/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const HHouseholdIdIndexRoute = HHouseholdIdIndexRouteImport.update({
  id: '/h/$householdId/',
  path: '/h/$householdId/',
  getParentRoute: () => rootRouteImport,
} as any)
const HHouseholdIdSettingsRoute = HHouseholdIdSettingsRouteImport.update({
  id: '/h/$householdId/settings',
  path: '/h/$householdId/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HHouseholdIdImportRoute = HHouseholdIdImportRouteImport.update({
  id: '/h/$householdId/import',
  path: '/h/$householdId/import',
  getParentRoute: () => rootRouteImport,
} as any)
const HHouseholdIdRRecipeIdIndexRoute =
  HHouseholdIdRRecipeIdIndexRouteImport.update({
    id: '/h/$householdId/r/$recipeId/',
    path: '/h/$householdId/r/$recipeId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const HHouseholdIdRRecipeIdEditRoute =
  HHouseholdIdRRecipeIdEditRouteImport.update({
    id: '/h/$householdId/r/$recipeId/edit',
    path: '/h/$householdId/r/$recipeId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/following/': typeof FollowingIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/h/$householdId/import': typeof HHouseholdIdImportRoute
  '/h/$householdId/settings': typeof HHouseholdIdSettingsRoute
  '/h/$householdId/': typeof HHouseholdIdIndexRoute
  '/h/$householdId/r/$recipeId/edit': typeof HHouseholdIdRRecipeIdEditRoute
  '/h/$householdId/r/$recipeId/': typeof HHouseholdIdRRecipeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/following': typeof FollowingIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/h/$householdId/import': typeof HHouseholdIdImportRoute
  '/h/$householdId/settings': typeof HHouseholdIdSettingsRoute
  '/h/$householdId': typeof HHouseholdIdIndexRoute
  '/h/$householdId/r/$recipeId/edit': typeof HHouseholdIdRRecipeIdEditRoute
  '/h/$householdId/r/$recipeId': typeof HHouseholdIdRRecipeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/following/': typeof FollowingIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/h/$householdId/import': typeof HHouseholdIdImportRoute
  '/h/$householdId/settings': typeof HHouseholdIdSettingsRoute
  '/h/$householdId/': typeof HHouseholdIdIndexRoute
  '/h/$householdId/r/$recipeId/edit': typeof HHouseholdIdRRecipeIdEditRoute
  '/h/$householdId/r/$recipeId/': typeof HHouseholdIdRRecipeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/search'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/reset'
    | '/auth/signup'
    | '/auth/update-password'
    | '/following/'
    | '/onboarding/'
    | '/h/$householdId/import'
    | '/h/$householdId/settings'
    | '/h/$householdId/'
    | '/h/$householdId/r/$recipeId/edit'
    | '/h/$householdId/r/$recipeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/search'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/reset'
    | '/auth/signup'
    | '/auth/update-password'
    | '/following'
    | '/onboarding'
    | '/h/$householdId/import'
    | '/h/$householdId/settings'
    | '/h/$householdId'
    | '/h/$householdId/r/$recipeId/edit'
    | '/h/$householdId/r/$recipeId'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/search'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/reset'
    | '/auth/signup'
    | '/auth/update-password'
    | '/following/'
    | '/onboarding/'
    | '/h/$householdId/import'
    | '/h/$householdId/settings'
    | '/h/$householdId/'
    | '/h/$householdId/r/$recipeId/edit'
    | '/h/$householdId/r/$recipeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthUpdatePasswordRoute: typeof AuthUpdatePasswordRoute
  FollowingIndexRoute: typeof FollowingIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  HHouseholdIdImportRoute: typeof HHouseholdIdImportRoute
  HHouseholdIdSettingsRoute: typeof HHouseholdIdSettingsRoute
  HHouseholdIdIndexRoute: typeof HHouseholdIdIndexRoute
  HHouseholdIdRRecipeIdEditRoute: typeof HHouseholdIdRRecipeIdEditRoute
  HHouseholdIdRRecipeIdIndexRoute: typeof HHouseholdIdRRecipeIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/following/': {
      id: '/following/'
      path: '/following'
      fullPath: '/following/'
      preLoaderRoute: typeof FollowingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/update-password': {
      id: '/auth/update-password'
      path: '/auth/update-password'
      fullPath: '/auth/update-password'
      preLoaderRoute: typeof AuthUpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/auth/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/h/$householdId/': {
      id: '/h/$householdId/'
      path: '/h/$householdId'
      fullPath: '/h/$householdId/'
      preLoaderRoute: typeof HHouseholdIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/h/$householdId/settings': {
      id: '/h/$householdId/settings'
      path: '/h/$householdId/settings'
      fullPath: '/h/$householdId/settings'
      preLoaderRoute: typeof HHouseholdIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/h/$householdId/import': {
      id: '/h/$householdId/import'
      path: '/h/$householdId/import'
      fullPath: '/h/$householdId/import'
      preLoaderRoute: typeof HHouseholdIdImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/h/$householdId/r/$recipeId/': {
      id: '/h/$householdId/r/$recipeId/'
      path: '/h/$householdId/r/$recipeId'
      fullPath: '/h/$householdId/r/$recipeId/'
      preLoaderRoute: typeof HHouseholdIdRRecipeIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/h/$householdId/r/$recipeId/edit': {
      id: '/h/$householdId/r/$recipeId/edit'
      path: '/h/$householdId/r/$recipeId/edit'
      fullPath: '/h/$householdId/r/$recipeId/edit'
      preLoaderRoute: typeof HHouseholdIdRRecipeIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetRoute: AuthResetRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthUpdatePasswordRoute: AuthUpdatePasswordRoute,
  FollowingIndexRoute: FollowingIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  HHouseholdIdImportRoute: HHouseholdIdImportRoute,
  HHouseholdIdSettingsRoute: HHouseholdIdSettingsRoute,
  HHouseholdIdIndexRoute: HHouseholdIdIndexRoute,
  HHouseholdIdRRecipeIdEditRoute: HHouseholdIdRRecipeIdEditRoute,
  HHouseholdIdRRecipeIdIndexRoute: HHouseholdIdRRecipeIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
